# bayesian_surprise_simple_example.R
# 5/08/2021
# A simple example showing how Bayesian Surprise can be calculated from an initial sequence based on
# the relative freq/probabilities of each element. A Bayesian model is constructed from prior data P(M),
# and the likelihood P(D|M). New evidence P(D) is used to finally calculate the posterior P(M|D).

# create example data sequence
database <- "a-c-abc-abc-aa-bcb-bcb-bcb-aa-aaa-ac-ab-a-a-a-c-c-c-a-c-aa-aa-aa-bbb-bbb-abc-bbb-b-b-b-cba-aaa-bbb-ccc-aab"
ex1 <- "a-b-abcabc-aa-aa-ac-ab-aac-b-a"
ex2 <- c("a-a-b", "a-b-a-a-b", "b-b-b-b-a","abc","aa-aa-ac","a-b-c","c-b-c")
ex3 <- "a-c-abc-abc-aa-aa-ac-ab-aac-b-a"
ex4 <- "a-b-abcabc-aa-aa-ac-abdc-aac-b-a-c"
database.seq <- seqdef(database)
ex1.seq <- seqdef(ex1)
ex2.seq <- seqdef(ex2)
ex3.seq <- seqdef(ex3)
ex4.seq <- seqdef(ex4)

# build the probabilistic suffix tree
database.pst <- pstree(database.seq, L=2, nmin = 2)

results <- PST::predict(database.pst, database.seq, decomp = TRUE, output = "prob")
           PST::predict(database.pst, ex2.seq, decomp = TRUE, output = "prob")
newsymbols <- novel.sequences(ex1,results)  # send unconverted string sequence, send probability values
database2 <- addseq.database(database,newsymbols)

### FIX NOVEL.SEQUENCES FUNCTION



### STOP HERE ##############

# Extracting contexts in a PST satisfying user defined criterion
cmine(database.pst, pmin = 0.8, state = "ccc")

# An outlier is defined as a sequence that is unlikely to have been generated by the model.
query(database.pst,"abc",output = "prob", exact=TRUE)

# predict the probability of NEW categorical sequences, i.e. the evidence or new data P(D)
probs <- PST::predict(database.pst, ex4.seq, decomp=TRUE,output = "prob") 
probs[is.na(probs)] <- 0
print(probs)
## --------------------

ex1.seq.event <- seqecreate(ex1.seq)
seqistatd(ex1.seq)    # State frequencies in each individual sequence

# calculate relative frequencies and hence probabilities
seqlength <- seqelength(ex1.seq.event)
statseq <- seqstatf(ex1.seq)
statseq[,3] <- statseq[,1]/seqlength; 
colnames(statseq)[3] <- "RelativeFreqs"
print(statseq,digits=3)

# get the probabilities of a sequence, same results as relative frequencies in statseq[,3] code above.
cprob(ex1.seq, L = 0, prob = TRUE)



